<?php declare(strict_types=1);
namespace Belin\Sql\Reflection;

use Belin\Sql\DataAnnotations\Column;
use Belin\Sql\DataAnnotations\DatabaseGenerated;
use Belin\Sql\DataAnnotations\DatabaseGeneratedOption;

/**
 * Provides information about a database column.
 */
final class ColumnInfo {

	/**
	 * Value indicating whether the column can be read.
	 */
	public readonly bool $canRead;

	/**
	 * Value indicating whether the column can be written to.
	 */
	public readonly bool $canWrite;

	/**
	 * Value indicating whether the column value is generated by the database.
	 */
	public readonly bool $isComputed;

	/**
	 * Value indicating whether the column value is generated by the database when a row is inserted.
	 */
	public readonly bool $isIdentity;

	/**
	 * Value indicating whether the column value is nullable.
	 */
	public readonly bool $isNullable;

	/**
	 * The column name.
	 */
	public readonly string $name;

	/**
	 * The type of the column value.
	 */
	public readonly \ReflectionType $type;

	/**
	 * The property information providing the column metadata.
	 */
	private readonly \ReflectionProperty $property;

	/**
	 * Creates new column information.
	 * @param \ReflectionProperty $property The property information providing the column metadata.
	 */
	public function __construct(\ReflectionProperty $property) {
		$column = array_first($property->getAttributes(Column::class))?->newInstance() ?? new Column($property->name);
		$databaseGenerated = array_first($property->getAttributes(DatabaseGenerated::class))?->newInstance() ?? new DatabaseGenerated(DatabaseGeneratedOption::None);
		$type = $property->getType();

		$this->canRead = true;
		$this->canWrite = !$property->isReadOnly();
		$this->isComputed = $databaseGenerated->databaseGeneratedOption != DatabaseGeneratedOption::None;
		$this->isIdentity = $databaseGenerated->databaseGeneratedOption == DatabaseGeneratedOption::Identity;
		$this->isNullable = $type->allowsNull();
		$this->name = $column->name;
		$this->property = $property;
		$this->type = $type;
	}

	/**
	 * Gets the property value of a specified object.
	 * @param object $instance The object whose property value will be returned.
	 * @return mixed The property value of the specified object.
	 */
	public function getValue(object $instance): mixed {
		return $this->property->getValue($instance);
	}

	/**
	 * Sets the property value of a specified object.
	 * @param object $instance The object whose property value will be set.
	 * @param mixed $value The new property value.
	 */
	public function setValue(object $instance, mixed $value): void {
		$this->property->setValue($instance, $value);
	}
}
