<?php declare(strict_types=1);
namespace Belin\Sql\Reflection;

use Belin\Sql\DataAnnotations\Column;
use Belin\Sql\DataAnnotations\DatabaseGenerated;
use Belin\Sql\DataAnnotations\DatabaseGeneratedOption;
use ReflectionProperty;

/**
 * Provides information about a database column.
 */
final class ColumnInfo {

	/**
	 * Value indicating whether the column can be read.
	 */
	public readonly bool $canRead;

	/**
	 * Value indicating whether the column can be written to.
	 */
	public readonly bool $canWrite;

	/**
	 * Value indicating whether the column value is generated by the database.
	 */
	public readonly bool $isComputed;

	/**
	 * Value indicating whether the column value is generated by the database when a row is inserted.
	 */
	public readonly bool $isIdentity;

	/**
	 * Value indicating whether the column value is nullable.
	 */
	public readonly bool $isNullable;

	/**
	 * The column name.
	 */
	public readonly string $name;

	/**
	 * The type of the column value.
	 */
	public readonly string $type;

	/**
	 * Creates new column information.
	 * @param \ReflectionProperty $property The property information providing the column metadata.
	 */
	public function __construct(\ReflectionProperty $property) {
		$column = array_first($property->getAttributes(Column::class))?->newInstance() ?? new Column($property->name);
		$this->name = $column->name;
		$this->canRead = true;
		$this->canWrite = !$property->isReadOnly();

		$databaseGenerated = array_first($property->getAttributes(DatabaseGenerated::class))?->newInstance() ?? new DatabaseGenerated(DatabaseGeneratedOption::None);
		$this->isComputed = $databaseGenerated->databaseGeneratedOption != DatabaseGeneratedOption::None;
		$this->isIdentity = $databaseGenerated->databaseGeneratedOption == DatabaseGeneratedOption::Identity;

		$propertyType = $property->getType();
		$this->isNullable = $propertyType->allowsNull();
		$this->type = $propertyType->getName();
	}
}
